[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=4096"

[context.production.environment]
  REACT_APP_API_BASE_URL = "https://79.76.48.165"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"