services:
  recommendation-service:
    image: recommendation-service:latest
    build:
      context: ./recommendation-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka/
    depends_on:
      - eureka-server
    volumes:
      - recommendation-data:/data

  statistics-service:
    image: statistics-service:latest
    build:
      context: ./statistics-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka/
    depends_on:
      - eureka-server
    volumes:
      - statistics-data:/data

  user-tracking-service:
    image: user-tracking-service:latest
    build:
      context: ./user-tracking-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka/
    depends_on:
      - eureka-server
    volumes:
      - user-tracking-data:/data

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka/
    depends_on:
      - eureka-server

  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
      dockerfile: ./Dockerfile
    ports:
      - "8762:8762"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8762

volumes:
  recommendation-data:
  statistics-data:
  user-tracking-data:
