services:
  recommendation-service:
    image: recommendation-service:latest
    build:
      context: ./recommendation-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
    volumes:
      - recommendation-data:/data

  statistics-service:
    image: statistics-service:latest
    build:
      context: ./statistics-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
    volumes:
      - statistics-data:/data

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  recommendation-data:
  statistics-data:
