services:
  user-tracking-service:
    image: user-tracking-service:latest
    build:
      context: ./user-tracking-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
    volumes:
      - user-tracking-data:/data

  recommendation-service:
    image: recommendation-service:latest
    build:
      context: ./recommendation-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
    volumes:
      - recommendation-data:/data

  statistics-service:
    image: statistics-service:latest
    build:
      context: ./statistics-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
    volumes:
      - statistics-data:/data

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server

  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  frontend:
    image: frontend:latest
    build:
      context: ./frontend
    ports:
      - "3000:3000"

volumes:
  user-tracking-data:
  recommendation-data:
  statistics-data:
