services:
  # Place Eureka server first with healthcheck
  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
      dockerfile: ./Dockerfile
    ports:
      - "8762:8762"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8762
    healthcheck:
      test: "wget -q --spider http://localhost:8762/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # API Gateway depends on healthy Eureka server
  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy

  # Microservices depend on healthy Eureka server
  recommendation-service:
    image: recommendation-service:latest
    build:
      context: ./recommendation-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    volumes:
      - recommendation-data:/data

  statistics-service:
    image: statistics-service:latest
    build:
      context: ./statistics-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    volumes:
      - statistics-data:/data

  user-tracking-service:
    image: user-tracking-service:latest
    build:
      context: ./user-tracking-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8762/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    volumes:
      - user-tracking-data:/data

volumes:
  recommendation-data:
  statistics-data:
  user-tracking-data:
