server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: recommendation-service
          uri: ${RECOMMENDATION_SERVICE_URL:lb://recommendation-service}
          predicates:
            - Path=/recommendation/**
        - id: statistics-service
          uri: ${STATISTICS_SERVICE_URL:lb://statistics-service}
          predicates:
            - Path=/statistics/**
        - id: user-tracking-service
          uri: ${USER_TRACKING_SERVICE_URL:lb://user-tracking-service}
          predicates:
            - Path=/user-tracking/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Docker profile
---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

# Production profile for cloud deployment (Oracle Cloud)
---
spring:
  config:
    activate:
      on-profile: production
  cloud:
    gateway:
      routes:
        - id: recommendation-service
          uri: ${RECOMMENDATION_SERVICE_URL}
          predicates:
            - Path=/recommendation/**
        - id: statistics-service
          uri: ${STATISTICS_SERVICE_URL}
          predicates:
            - Path=/statistics/**
        - id: user-tracking-service
          uri: ${USER_TRACKING_SERVICE_URL}
          predicates:
            - Path=/user-tracking/**

# Self-ping configuration to keep the service alive
app:
  self-ping:
    enabled: true
    service-url: http://${ORACLE_EXTERNAL_HOSTNAME}:8080/actuator/health

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${ORACLE_EXTERNAL_HOSTNAME}
    non-secure-port-enabled: true
    secure-port-enabled: false
    prefer-ip-address: false
