server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: recommendation-service
          uri: ${RECOMMENDATION_SERVICE_URL:lb://recommendation-service}
          predicates:
            - Path=/recommendation/**
          filters:
            - RewritePath=/recommendation(?<segment>/?.*), /recommendation$\{segment}
        - id: statistics-service
          uri: ${STATISTICS_SERVICE_URL:lb://statistics-service}
          predicates:
            - Path=/statistics/**
          filters:
            - RewritePath=/statistics(?<segment>/?.*), /statistics$\{segment}
        - id: user-tracking-service
          uri: ${USER_TRACKING_SERVICE_URL:lb://user-tracking-service}
          predicates:
            - Path=/user-tracking/**
          filters:
            - RewritePath=/user-tracking(?<segment>/?.*), /user-tracking$\{segment}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

# Docker profile
---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

# Production profile for cloud deployment (Oracle Cloud)
---
spring:
  config:
    activate:
      on-profile: production
  cloud:
    gateway:
      routes:
        - id: recommendation-service
          uri: ${RECOMMENDATION_SERVICE_URL}
          predicates:
            - Path=/recommendation/**
          filters:
            - RewritePath=/recommendation(?<segment>/?.*), /recommendation$\{segment}
        - id: statistics-service
          uri: ${STATISTICS_SERVICE_URL}
          predicates:
            - Path=/statistics/**
          filters:
            - RewritePath=/statistics(?<segment>/?.*), /statistics$\{segment}
        - id: user-tracking-service
          uri: ${USER_TRACKING_SERVICE_URL}
          predicates:
            - Path=/user-tracking/**
          filters:
            - RewritePath=/user-tracking(?<segment>/?.*), /user-tracking$\{segment}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${ORACLE_EXTERNAL_HOSTNAME}
    non-secure-port-enabled: true
    secure-port-enabled: false

