server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true  # Important for preflight handling
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - https://musicanalytics.netlify.app
              - https://music-analytics.abenezeranglo.uk
              - http://localhost:3000
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            exposedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: eureka-server-apps
          uri: ${EUREKA_SERVER_URL:lb://eureka-server}
          predicates:
            - Path=/eureka/services
          filters:
            - RewritePath=/eureka/services, /eureka/apps
            - AddResponseHeader=Access-Control-Allow-Origin, https://musicanalytics.netlify.app
            - AddResponseHeader=Access-Control-Allow-Methods, GET,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type
            - AddResponseHeader=Access-Control-Allow-Credentials, true

        - id: actuator-routes
          uri: lb://api-gateway
          predicates:
            - Path=/actuator/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, https://musicanalytics.netlify.app
            - AddResponseHeader=Access-Control-Allow-Methods, GET,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type
            - AddResponseHeader=Access-Control-Allow-Credentials, true

        - id: recommendation-service
          uri: ${RECOMMENDATION_SERVICE_URL:lb://recommendation-service}
          predicates:
            - Path=/recommendation/**
          filters:
            - RewritePath=/recommendation(?<segment>/?.*), /recommendation$\{segment}
            - AddResponseHeader=Access-Control-Allow-Origin, https://musicanalytics.netlify.app
            - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,PUT,DELETE,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type,Authorization
            - AddResponseHeader=Access-Control-Allow-Credentials, true
            - AddResponseHeader=Access-Control-Max-Age, 3600
        - id: statistics-service
          uri: ${STATISTICS_SERVICE_URL:lb://statistics-service}
          predicates:
            - Path=/statistics/**
          filters:
            - RewritePath=/statistics(?<segment>/?.*), /statistics$\{segment}
            - AddResponseHeader=Access-Control-Allow-Origin, https://musicanalytics.netlify.app
            - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,PUT,DELETE,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type,Authorization
            - AddResponseHeader=Access-Control-Allow-Credentials, true
            - AddResponseHeader=Access-Control-Max-Age, 3600
        - id: user-tracking-service
          uri: ${USER_TRACKING_SERVICE_URL:lb://user-tracking-service}
          predicates:
            - Path=/user-tracking/**
          filters:
            - RewritePath=/user-tracking(?<segment>/?.*), /user-tracking$\{segment}
            - AddResponseHeader=Access-Control-Allow-Origin, https://musicanalytics.netlify.app
            - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,PUT,DELETE,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type,Authorization
            - AddResponseHeader=Access-Control-Allow-Credentials, true
            - AddResponseHeader=Access-Control-Max-Age, 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

security:
  enabled: false

# Docker profile
---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

# Production profile for cloud deployment (Oracle Cloud)
---
spring:
  config:
    activate:
      on-profile: production
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true  # Important for preflight handling
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - https://musicanalytics.netlify.app
              - https://music-analytics.abenezeranglo.uk
              - http://localhost:3000
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            exposedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: eureka-server-apps
          uri: http://eureka-server:8761
          predicates:
            - Path=/eureka/services
          filters:
            - RewritePath=/eureka/services, /eureka/apps
            - AddResponseHeader=Access-Control-Allow-Origin, https://musicanalytics.netlify.app
            - AddResponseHeader=Access-Control-Allow-Methods, GET,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type
            - AddResponseHeader=Access-Control-Allow-Credentials, true

        - id: actuator-routes
          uri: lb://api-gateway
          predicates:
            - Path=/actuator/**
          filters:
            - AddResponseHeader=Access-Control-Allow-Origin, https://musicanalytics.netlify.app
            - AddResponseHeader=Access-Control-Allow-Methods, GET,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type
            - AddResponseHeader=Access-Control-Allow-Credentials, true

        - id: recommendation-service
          uri: ${RECOMMENDATION_SERVICE_URL}
          predicates:
            - Path=/recommendation/**
          filters:
            - RewritePath=/recommendation(?<segment>/?.*), /recommendation$\{segment}
            - AddResponseHeader=Access-Control-Allow-Origin, https://musicanalytics.netlify.app
            - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,PUT,DELETE,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type,Authorization
            - AddResponseHeader=Access-Control-Allow-Credentials, true
            - AddResponseHeader=Access-Control-Max-Age, 3600
        - id: statistics-service
          uri: ${STATISTICS_SERVICE_URL}
          predicates:
            - Path=/statistics/**
          filters:
            - RewritePath=/statistics(?<segment>/?.*), /statistics$\{segment}
            - AddResponseHeader=Access-Control-Allow-Origin, https://musicanalytics.netlify.app
            - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,PUT,DELETE,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type,Authorization
            - AddResponseHeader=Access-Control-Allow-Credentials, true
            - AddResponseHeader=Access-Control-Max-Age, 3600
        - id: user-tracking-service
          uri: ${USER_TRACKING_SERVICE_URL}
          predicates:
            - Path=/user-tracking/**
          filters:
            - RewritePath=/user-tracking(?<segment>/?.*), /user-tracking$\{segment}
            - AddResponseHeader=Access-Control-Allow-Origin, https://musicanalytics.netlify.app
            - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,PUT,DELETE,OPTIONS
            - AddResponseHeader=Access-Control-Allow-Headers, Content-Type,Authorization
            - AddResponseHeader=Access-Control-Allow-Credentials, true
            - AddResponseHeader=Access-Control-Max-Age, 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${ORACLE_EXTERNAL_HOSTNAME}
    non-secure-port-enabled: true
    secure-port-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

