server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - https://musicanalytics.netlify.app
              - https://music-analytics.abenezeranglo.uk
              - http://localhost:3000
            allowedHeaders: "*"
            allowedMethods:
              - GET 
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: api-gateway
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always