server:
  port: 8084

spring:
  application:
    name: user-tracking-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    hostname: user-tracking-service
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
    instanceId: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always