server:
  port: 8083

spring:
  application:
    name: statistics-service
  datasource:
    url: jdbc:h2:mem:statisticsdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Profiles configuration
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:h2:mem:statisticsdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

# Production profile for cloud deployment (Oracle Cloud)
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:h2:mem:statisticsdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# Self-ping configuration to keep the service alive
app:
  self-ping:
    enabled: true
    service-url: http://${ORACLE_EXTERNAL_HOSTNAME}:8080/statistics/topTracks

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${ORACLE_EXTERNAL_HOSTNAME}
    non-secure-port-enabled: true
    secure-port-enabled: false
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90