server:
  port: 8762

spring:
  application:
    name: eureka-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: production

# Self-ping configuration to keep the service alive
app:
  self-ping:
    enabled: true
    service-url: https://${RENDER_EXTERNAL_HOSTNAME}/eureka/

eureka:
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME}
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    prefer-ip-address: false
