server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

# Default configuration
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always

---
# Production profile configuration
spring:
  config:
    activate:
      on-profile: production

eureka:
  instance:
    hostname: ${ORACLE_EXTERNAL_HOSTNAME}
    non-secure-port-enabled: true
    secure-port-enabled: false
    prefer-ip-address: false
    
---
# Docker profile configuration
spring:
  config:
    activate:
      on-profile: docker

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always

