name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install
      working-directory: .

    - name: Build Docker images
      run: docker-compose build

    - name: Run unit tests
      run: mvn test
      working-directory: .

    - name: Run integration tests
      run: mvn verify
      working-directory: .

    - name: Set up database
      run: |
        docker-compose up -d db
        sleep 10 # wait for the database to be ready

    - name: Run database migrations
      run: mvn flyway:migrate
      working-directory: .
