name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker images
      run: docker-compose build

    - name: Run unit tests
      run: mvn test

    - name: Run integration tests
      run: mvn verify

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/user-tracking-service-deployment.yaml
        kubectl apply -f k8s/recommendation-service-deployment.yaml
        kubectl apply -f k8s/statistics-service-deployment.yaml
        kubectl apply -f k8s/api-gateway-deployment.yaml
        kubectl apply -f k8s/eureka-server-deployment.yaml
