name: Deploy to Oracle VM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Verify Maven Configuration
      run: |
        echo "Checking Maven setup..."
        echo "JAVA_HOME: $JAVA_HOME"
        mvn -version
        ls -la ~/.m2 || true
        
    - name: Setup Maven Settings
      run: |
        mkdir -p ~/.m2
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"
                 xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <servers>
            <server>
              <id>central</id>
              <username>${{ secrets.MAVEN_USERNAME }}</username>
              <password>${{ secrets.MAVEN_PASSWORD }}</password>
            </server>
          </servers>
        </settings>' > ~/.m2/settings.xml

    - name: Build with Maven
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      run: |
        mvn -B -s ~/.m2/settings.xml clean install -DskipTests

    - name: Verify Build Artifacts
      run: |
        for service in api-gateway eureka-server recommendation-service statistics-service user-tracking-service; do
          if [ -f "$service/target/$service-1.0-SNAPSHOT.jar" ]; then
            echo "$service build successful"
          else
            echo "Error: $service build failed - JAR not found"
            exit 1
          fi
        done

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Oracle Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.OCI_REGISTRY }}
        username: ${{ secrets.OCI_USERNAME }}
        password: ${{ secrets.OCI_AUTH_TOKEN }}

    - name: Build and Push Docker Images
      env:
        REGISTRY: ${{ secrets.OCI_REGISTRY }}
        NAMESPACE: ${{ secrets.OCI_NAMESPACE }}
      run: |
        services=("api-gateway" "eureka-server" "recommendation-service" "statistics-service" "user-tracking-service")
        for service in "${services[@]}"; do
          echo "Building and pushing $service..."
          docker build -t ${REGISTRY}/${NAMESPACE}/$service:latest -f $service/Dockerfile .
          docker push ${REGISTRY}/${NAMESPACE}/$service:latest
        done

    - name: Log out from Oracle Container Registry
      if: ${{ always() }}
      run: docker logout ${{ secrets.OCI_REGISTRY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
      REGISTRY: ${{ secrets.OCI_REGISTRY }}
      OCI_USERNAME: ${{ secrets.OCI_USERNAME }}
      OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Oracle Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.OCI_REGISTRY }}
        username: ${{ secrets.OCI_USERNAME }}
        password: ${{ secrets.OCI_AUTH_TOKEN }}

    - name: Verify VM Connection
      env:
        ORACLE_VM_IP: ${{ secrets.ORACLE_VM_IP }}
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem opc@${ORACLE_VM_IP} echo "VM connection successful" || {
          echo "Failed to connect to VM"
          exit 1
        }

    - name: Deploy to Oracle VM
      env:
        ORACLE_VM_IP: ${{ secrets.ORACLE_VM_IP }}
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem opc@${ORACLE_VM_IP} << 'EOF'
          echo "Deploying to VM..."
          cd ~/music-analytics/vm-deploy || exit 1
          docker login ${REGISTRY} -u ${OCI_USERNAME} -p ${OCI_AUTH_TOKEN} || exit 1
          docker-compose pull || { docker logout ${REGISTRY}; exit 1; }
          docker-compose up -d || { docker logout ${REGISTRY}; exit 1; }
          docker logout ${REGISTRY}
          echo "Deployment completed successfully"
        EOF
        rm -f ssh_key.pem

    - name: Log out from Oracle Container Registry
      if: ${{ always() }}
      run: docker logout ${{ secrets.OCI_REGISTRY }}
